### ISSUE TITLE
port 5000 reserved on Apple MacBook

### ISSUE THREAD

**Issue by Affan-Rehman** [Harri200191/Audio_Analysis_UI_UX#1]
### Dealing with AirPlay Receiver on MacBook Blocking Port 5000

If you encounter issues running a backend server because port 5000 is reserved for the AirPlay receiver on your MacBook, there are two solutions:

1. **Turn off AirPlay Receiver on Mac:**
   - Navigate to System Preferences.
   - Search for "AirPlay Receiver" and disable it.

2. **Change the Code to Use Another Port:**
   - Modify the code to utilize a port other than 5000.

**Comment by Harri200191** [comment]
Thanks for making the applicational cross platform functional 😊
